### ISSUE TITLE
Compiler error due to extraneous comma

### ISSUE THREAD

**Issue by lizziel** [GEOS-ESM/GMAO_Shared#104]
I tried building the latest main and get an error when compiling with ifort18 due to this line: 
https://github.com/GEOS-ESM/GMAO_Shared/blob/d4dc835456bea32ae0c2518add1b32115171402f/GEOS_Shared/lightning_toolbox_mod.F90#L200

Removing the comma gets around the issue.

**Comment by mathomp4** [comment]
@lizziel I agree it's bad OpenMP and should be fixed, but there is another issue. 

The only way you could have triggered that is with a `PUBLIC` OpenMP declaration in a CMakeLists.txt somewhere.

You might encounter all sorts of issues with GEOS if you do that as we turn on OpenMP very selectively (with `PRIVATE` usually). Do you know what triggered OpenMP building here?

**Comment by lizziel** [comment]
@mathomp4 Thanks for the tip. I suspect this may be in HEMCO and will report back what I find.

**Comment by mathomp4** [comment]
@lizziel That said, I should make a PR for the bug...
