### ISSUE TITLE
regrid_forcing.x crashes in MAPL

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GMAO_Shared#120]
I think this is an easy one for @bena-nasa or @tclune, but it was beyond me. 

In trying to make new SSTs/ICE files for @wmputman, I tried running `regrid_forcing.x` (and `regrid_forcing_esmf.x`) from a recent build of GEOS. I first tried the stock GEOSgcm with MAPL 2.1.6 and it failed in MAPL_Generic. I then tried a MAPL `develop` build, and it died same place (though line numbers different):
```
regrid_forcing_es  000000000048D6BC  mapl_genericmod_m        4549  MAPL_Generic.F90
regrid_forcing_es  000000000041EBD6  MAIN__                    595  regrid_forcing_esmf.F90
```
This is:
```fortran
   call lgr%debug('Adding logger for component %a ',trim(fname))
```

My guess is `regrid_forcing.F90` (and `regrid_forcing_esmf.F90`?) need some MAPL initialization magic to get it working. 

Note: I'm adding @sanAkel to this just so he's aware of this.

**Comment by tclune** [comment]
Any MAPL application now (as of version x.y.z) requires initialization.   The procedures are `MAPL_Initialize()` (and finalize) in `./base/ApplicationSupport.F90`
