### ISSUE TITLE
Concerning PBS code in gcmpost.script

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GMAO_Shared#128]
This is a call to @sdrabenh and @lltakacs at the least. NCCS has been having issues with people's gcm_post jobs making nodes crawl. Now, I think a lot of that is due to older tags using `PBS_NODEFILE` in a bad way. Our `gcm_post.j` in GEOSgcm at least looks good (uses `SLURM_NTASKS` if on NCCS). But I was looking around and saw this:

https://github.com/GEOS-ESM/GMAO_Shared/blob/81e7ff442f43ff5160412e02550670218d279cc1/GEOS_Util/post/gcmpost.script#L240-L251

If one of you could help me translate that, I think I can make it "pure" SLURM for NCCS. I think I know how to detect "if batch" in SLURM, I just want to make sure I capture all of what it's doing.

**Comment by lltakacs** [comment]
Matt, I would think that the logic used in gcm_run.j would be appropriate:

if ($?SLURM_NTASKS) then
   set  NCPUS = $SLURM_NTASKS
else if ($?PBS_NODEFILE) then
   set  NCPUS = `cat $PBS_NODEFILE | wc -l`
else
   set  NCPUS = NULL
endif

**Comment by mathomp4** [comment]
@lltakacs Okay. I'll make a PR to try that out. Though I might need you or @sdrabenh to test it. `gcmpost.script`, et al are sort of black boxes I avoid and assume work. 😄
