### ISSUE TITLE
Request for newer version of FMS

### ISSUE THREAD

**Issue by atrayano** [GEOS-ESM/GMAO_Shared#14]
mom6 apparently requires more recent version of FMS. The latest release from GFDL is xanadu (although mom6-examples refers to a FMS @ f2e2c86, which is the latest on the master branch)

**Comment by tclune** [comment]
When we go to MOM6, we should fork FMS into a separate repository under GEOS-ESM.    We could still include it underneath GMAO_Shared if that is desired.

**Comment by mathomp4** [comment]
> When we go to MOM6, we should fork FMS into a separate repository under GEOS-ESM. We could still include it underneath GMAO_Shared if that is desired.

If we do this, we need to be careful, or mindful at least. Xanadu is a few months behind the `master` of FMS. Not a big problem as it looks like 99% of the changes since then are Ed Hartnett adding Autotools.

What's more exciting is that it would require careful, but not impossible, CMake update from @tclune and myself as a pure clone of FMS into GEOS would pull the real source code out of the current `GFDL_fms/shared` directory to directly into `GFDL_fms`.

**Comment by mathomp4** [comment]
Hmm. Actually, it might be worth the effort. It looks like the test with the JEDI FMS I did a while back has quite a few differences with Xanadu. I think they forked off of the `dev/master` of GFDL. From staring at the changes, some were by @aerorahul  and others seem to be bug fixes either from GFDL or JCSDA.

**Comment by mathomp4** [comment]
I suppose the "correct" thing would be to fork from NOAA-GFDL and then make a branch and, if nothing else. put the MAPL_MODE changes into that. 

There do seem to be a good chunk of changes on the JCSDA version that seem worthy bug fixes and I'm wondering if @aerorahul or Dan Holdaway could tell us if those are things we'll need to fix for GEOS as well? If so, we'd probably want to pull *those* edits into our branch (the ones that aren't on `master`).

**Comment by tclune** [comment]
Yes - fork of NOAA-GFDL can/must proceed in advance of other changes.

@aerorahul (on travel this week) has already looked into issues with integrating MOM6 within our cmake infrastructure.    I don't think it was completed before he left town, and it may be in the way of Santha's work.   I'll try to catch up with him today.  (His GitHub account request preceded our establishment of a process and thus he was missed until just now.)

**Comment by aerorahul** [comment]
If possible, please look at jcsda fork of fms and branch dev/master-ecbuild.

We have used this branch with both mom6 and standalone FV3.

I did not finish mom6 integration into our geos cmake.

If you are interested in seeing how the JEDI builds mom6 with FMS and other mom6 dependencies, see aerorahul/mom6-bundle

**Comment by tclune** [comment]
@aerorahul - we certainly want to get your branch pushed onto the GEOS-ESM fork of fms.     But I think our fork should be directly from GFDL.      I anticipate a bit of a mess in the future when high level apps try to determine just where to get libraries like FMS from ...

**Comment by mathomp4** [comment]
Well, going off of `NOAA-GFDL/FMS/master`, I at least have something that can build the library itself; I'm trying the model now. I'll probably do some baby steps. First the minimal change off of `master` and if all is zero-diff, commit. Then perhaps branch

**Comment by mathomp4** [comment]
I should say commit *and push* of course.

Eventually I'll need to consult @tclune on how to manage the external. For now I'm just sort of hard-coding in changes into this clone and getting things working first.

**Comment by mathomp4** [comment]
And one plus of forking off of GFDL's stock repo master is I can make another fork, where I disable those annoying `!DEC$ MESSAGE` and make a pull request to have them removed in master!

**Comment by aerorahul** [comment]
@tclune the changes in the jcsda fork are strictly in the CMakeLists.txt. So, no issue on forking directly from NOAA-GFDL. 
We can eventually reconcile. Also, when building JEDI interfaces with GEOS, we will use the FMS library compiled with GEOS, rather than the jcsda fork.

**Comment by mathomp4** [comment]
Well this is exciting. I committed and pushed some changes to my fork of FMS and guess what? It has a `.travis-ci.yml` file!

It is failing at present, though I'm not sure if it ever passed. Still, I think I have an inkling of what it's mad about and I'll fix that soon.

**Comment by mathomp4** [comment]
Okay. I have some results. I can build and run the model with both a minimally-different-from-master branch and one which has all the extra changes from JCSDA. If I compare that to our current FMS the answers are...sort of zero-diff?

If I compare a 1-day run of stock `GEOSgcm` `master` (v10.3.1 or `Jason-3_1`) to the new FMS I get zero diff except for:
```
Comparing NC4 fvcore_internal_checkpoint using nccmp...
Failure!
Checking for data differences
Variable Group Count          Sum      AbsSum          Min         Max       Range         Mean      StdDev
U        /     15954 -2.89844e-13 1.35394e-11 -1.42109e-14 1.42109e-14 2.84217e-14 -1.81675e-17 1.44738e-15
V        /     11219 -7.91107e-14 8.93166e-12 -2.13163e-14 1.77636e-14 3.90799e-14 -7.05149e-18 1.48342e-15
Checking for metadata differences

Comparing NC4 moist_import_checkpoint using nccmp...
Failure!
Checking for data differences
Variable Group Count         Sum      AbsSum         Min         Max Range        Mean StdDev
OMEGA    /         1 3.72529e-09 3.72529e-09 3.72529e-09 3.72529e-09     0 3.72529e-09      0
Checking for metadata differences

Comparing NC4 turb_import_checkpoint using nccmp...
Failure!
Checking for data differences
Variable Group Count         Sum      AbsSum         Min         Max Range        Mean StdDev
OMEGA    /         1 3.72529e-09 3.72529e-09 3.72529e-09 3.72529e-09     0 3.72529e-09      0
Checking for metadata differences
```
Nothing else is different. As for the "stock" HISTORY, everything is identical except one file of `geosgcm_prog`:
```
Comparing geosgcm_prog.20000415_0000z...
Success!
Comparing geosgcm_prog.20000415_0600z...
Success!
Comparing geosgcm_prog.20000415_1200z...
Failure!
Checking for data differences
Variable Group Count         Sum      AbsSum          Min         Max       Range        Mean      StdDev
OMEGA    /        13 8.73115e-10 1.51922e-08 -1.86265e-09 2.32831e-09 4.19095e-09 6.71627e-11 1.38192e-09
Comparing geosgcm_prog.20000415_1800z...
Success!
```
This said, the two branches I made are zero-diff to each other. So they are consistent.

**Comment by mathomp4** [comment]
All,

I have a new branch of `GEOSgcm` with the latest Xanadu FMS. The branch is `feature/xanadu-fms`. In this branch, FMS is now a new subrepository parallel to `GMAO_Shared`. I'll wait for @atrayano to test it out, but it seems to build and run for me.

**Comment by mathomp4** [comment]
I suppose this is now closed as we have moved to use FMS 2019.01.01

Is that correct @aerorahul, et al?

**Comment by aerorahul** [comment]
@mathomp4 if FMS 2019.01.01 is the default FMS, then I think this can be closed.

**Comment by mathomp4** [comment]
I like closing things.
