### ISSUE TITLE
Reconcile main and updates for the new GEOSadas-5_27_1_p2 tag coming to Git

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GMAO_Shared#161]
The GEOSadas is immanently releasing the first Git tag as the transition to Git. We have created a branch with updates from CVS relative to the initial release of the GMAO_Shared repository (back when the reflected the identical CVS state).  I've tried merging the release/cvs/GEOSadas-5_27_1_p2 branch where these changes have been accumulated into main to see what issues we might have as part of my ongoing tests to see what is needed to advance the GEOSadas to new model versions when ready. Here are the results the results from the latest attempt in GMAO_Shared with the candidate version:
```
Changes to be committed:
	modified:   GEOS_Shared/GEOS_Utilities.F90
	modified:   GEOS_Util/post/era5_prs2eta.F
	modified:   GEOS_Util/post/g5fcst_stats.pl
	modified:   GEOS_Util/post/stats.F90
	modified:   GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/cube_BCs.pl
	modified:   GMAO_etc/Extract_config.pm
	modified:   GMAO_etc/PUBLICTAG
	new file:   GMAO_etc/Recd_State.pm
	modified:   GMAO_etc/Remote_utils.pm
	modified:   GMAO_etc/ana4dupd.pl
	new file:   GMAO_etc/arbitrary.pl
	modified:   GMAO_etc/check_obsysrc.py
	modified:   GMAO_etc/cmpdir.pl
	modified:   GMAO_etc/getsponsor.pm
	modified:   GMAO_etc/idcheck.pl
	modified:   GMAO_etc/jobIDfilter
	modified:   GMAO_etc/mptfix.pl
	new file:   GMAO_etc/obsys-nccs-arc.rc
	modified:   GMAO_etc/obsys-nccs.rc
	modified:   GMAO_etc/rndasfiles
	modified:   GMAO_etc/rst2rcyc
	modified:   GMAO_hermes/cnv2prs.pl
	modified:   GMAO_hermes/dyn2dyn.f90
	modified:   GMAO_hermes/dyn_iupd.F90
	modified:   GMAO_hermes/dyn_recenter.f90
	modified:   GMAO_hermes/dyndiff.f90
	modified:   GMAO_hermes/dynp.f90
	modified:   GMAO_hermes/m_const.f90
	modified:   GMAO_hermes/m_dyn.f90
	modified:   GMAO_hermes/m_set_eta.F90
	modified:   GMAO_hermes/m_vdc2vdc.F90
	modified:   GMAO_ods/CMakeLists.txt
	modified:   GMAO_ods/diag2ods
	new file:   GMAO_ods/m_obs_stats.F90
	modified:   GMAO_ods/m_ods.f90
	modified:   GMAO_ods/obimp_summary.pl
	modified:   GMAO_ods/ods_dcget.f
	modified:   GMAO_ods/ods_dconv.f
	new file:   GMAO_ods/ods_diagnc4.f90
	modified:   GMAO_ods/odslist.f
	modified:   GMAO_ods/odsmatch.rc
	modified:   GMAO_ods/odsmeta.h
	modified:   GMAO_ods/odsnxtime.f
	modified:   GMAO_ods/odsstats.f
	modified:   GMAO_ods/ozone-kx.readme
	modified:   GMAO_ods/radiance-kx.readme
	modified:   GMAO_perllib/GrADS/Grads.pm
	modified:   GMAO_transf/g4tog5.f90
	modified:   GMAO_transf/m_xform.f90

Unmerged paths:
  (use "git add <file>..." to mark resolution)
	both modified:   GEOS_Util/plots/fcst/setup_statd
	both modified:   GEOS_Util/plots/grads_util/closeness.gs
	both modified:   GEOS_Util/plots/grads_util/corcmpz_plot.gs
	both modified:   GEOS_Util/plots/grads_util/makezf
	both modified:   GEOS_Util/plots/grads_util/parea
	both modified:   GEOS_Util/plots/grads_util/plot.rc
	both modified:   GEOS_Util/plots/grads_util/rmscmpz_plot.gs
	both modified:   GEOS_Util/plots/quickstat
	both modified:   GEOS_Util/plots/res/zonal.gs
	both modified:   GEOS_Util/post/gcmpost.script
	both modified:   GEOS_Util/post/regrid.pl
	both modified:   GMAO_etc/esma_mpirun
	both modified:   GMAO_hermes/CMakeLists.txt
	both modified:   GMAO_hermes/m_dyn_util.F90
	both modified:   GMAO_hermes/m_interpack.F
	both modified:   GMAO_hermes/m_interpack_ad.F
	both modified:   GMAO_hermes/m_mapz_pert.F90
```
 Note in particular the conflicts. These will have to be dealt with. I'm not sure who wins with the plots. The Hermes conflicts mostly do with the fact that on main those files now use the kind values (REAL32/REAL64) from the standard iso_fortran_env module rather than m_realkinds module. How, there appear to be some conflicts beyond just use the alternative definitions of the same kind.
For example in m_mapz_pert.F90 there is a routine mapz_pert_, in main the arguments are "real(kind=REAL64)", whereas on the cvs/adas branch these are plain "real", so for example should the real become "real(kind=32)" etc ...
In any case these conflicts will need to be resolved appropriately.

**Comment by sdrabenh** [comment]
@bena-nasa thanks for taking a first crack at this. I will look more carefully at these files this evening when I have time. Off the cuff I would say that main/v1.3.8 has @lltakacs latest plot updates as of 2021-02-12 brought over from his sandbox. In most cases I suspect git would supersede cvs for these. I do not recall many PRs lately dealing with GMAO_hermes on the git side. So it is possible that cvs is more up-to-date for that but @rtodling would know better than I. It may require a little tkcvs history for those conflicted lines. I suspect @mathomp4 could speak better regarding esma_mpirun.

**Comment by mathomp4** [comment]
For these files, my guess is `main` here wins for plots, post, and pre (though we'd want to be careful). Pretty much everything else, is probably "newer" in the CVS ADAS save `esma_mpirun` which I'd keep Git's version. 

Hermes is also mainly Ricardo's beat, so I'd trust his code, save for any places where (like Ben mentioned) we have a conflict due to type of argument!

**Comment by bena-nasa** [comment]
This xtrnames argument is unique to the now GEOSadas version of GMAO_Shared, so beyond all the other issues, any GMAO_Shared used by the model will be incompatible with the das until the two are merged.
```
GMAO_hermes/m_dyn.f90
1770:                        ncf, pncf, xtrnames )                                ! optional
1785:  character(len=*), OPTIONAL, intent(in), pointer :: xtrnames(:) ! name of addition tracers
```
as something in one of the das applications calls with this argument.

**Comment by mathomp4** [comment]
I'm going to close this. I think we've done it.
