### ISSUE TITLE
Endianness of GMAO_ods

### ISSUE THREAD

**Issue by bena-nasa** [GEOS-ESM/GMAO_Shared#21]
The GMAO_ods library was compiled with -convert big_endian in the CVS/GNUmake build.
The CMake version does not appear to be doing this

**Comment by mathomp4** [comment]
Sigh. I knew something else would need this. I was hoping we'd found all the directories that actually needed big-endian, but I guess not. I'll put in a fix.

**Comment by mathomp4** [comment]
Mentioning @gmao-msienkie so she can monitor this.
