### ISSUE TITLE
Regrid/Remapping of Restarts is broken for 2021 June to September

### ISSUE THREAD

**Issue by mathomp4** [GEOS-ESM/GMAO_Shared#302]
As discovered by Steve Guimond, `regrid.pl` and `remap_restarts.py` are broken for June 2021 to September 2021:

From `regrid.pl`:
```
Error. Mismatch between expid and fvcore ID
fvcore rst file: /archive/users/gmao_ops/MERRA2/gmao_ops/GEOSadas-5_12_4/d5124_m2_jan10/rs/Y2021/M08/d5124_m2_jun21.fvcore_internal_rst.20210809_21z.bin
INPUT expid: d5124_m2_jan10
fvcore ID:   d5124_m2_jun21
```

From `remap_restarts.py`:
```
Copy file /archive/users/gmao_ops/MERRA2/gmao_ops/GEOSadas-5_12_4/d5124_m2_jan10/rs/Y2021/M08/d5124_m2_jan10.fvcore_internal_rst.20210809_21z.bin to /gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Release/bin/20210809/merra2_tmp_2021080921//
Traceback (most recent call last):
  File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Release/bin/./remap_restarts.py", line 109, in <module>
    main(sys.argv[1:])
  File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Release/bin/./remap_restarts.py", line 93, in main
    upper = upperair(params_file=config_yaml)
  File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Release/bin/remap_upper.py", line 14, in __init__
    self.copy_merra2()
  File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Release/bin/remap_upper.py", line 300, in copy_merra2
    shutil.copy(f, dest)
  File "/usr/local/other/python/GEOSpyD/4.11.0_py3.9/2022-04-28/lib/python3.9/shutil.py", line 427, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/other/python/GEOSpyD/4.11.0_py3.9/2022-04-28/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/archive/users/gmao_ops/MERRA2/gmao_ops/GEOSadas-5_12_4/d5124_m2_jan10/rs/Y2021/M08/d5124_m2_jan10.fvcore_internal_rst.20210809_21z.bin'
```

Per a README by @rlucches (or @mssolomo?), the issue is that there was a rewind in MERRA-2 and the new restarts are prefixed by `d5124_m2_jun21` in the rewound segments and not `d5124_m2_jan10`. From what I see the `d5124_m2_jun21` restarts are only June to September.

**Comment by rlucches** [comment]
More info about the cause of this discontinuity can be found here:

https://www.nccs.nasa.gov/trac/esma/ticket/2206

Thanks,
Rob

On Mon, Nov 21, 2022 at 11:22:10AM -0800, Matthew Thompson wrote:
>    As discovered by Steve Guimond, regrid.pl and remap_restarts.py are
>    broken for June 2021 to September 2021:
> 
>    From regrid.pl:
> Error. Mismatch between expid and fvcore ID
> fvcore rst file: /archive/users/gmao_ops/MERRA2/gmao_ops/GEOSadas-5_12_4/d5124_m
> 2_jan10/rs/Y2021/M08/d5124_m2_jun21.fvcore_internal_rst.20210809_21z.bin
> INPUT expid: d5124_m2_jan10
> fvcore ID:   d5124_m2_jun21
> 
>    From remap_restarts.py:
> Copy file /archive/users/gmao_ops/MERRA2/gmao_ops/GEOSadas-5_12_4/d5124_m2_jan10
> /rs/Y2021/M08/d5124_m2_jan10.fvcore_internal_rst.20210809_21z.bin to /gpfsm/dnb4
> 4/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Release/bin/20210809/
> merra2_tmp_2021080921//
> Traceback (most recent call last):
>   File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Re
> lease/bin/./remap_restarts.py", line 109, in <module>
>     main(sys.argv[1:])
>   File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Re
> lease/bin/./remap_restarts.py", line 93, in main
>     upper = upperair(params_file=config_yaml)
>   File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Re
> lease/bin/remap_upper.py", line 14, in __init__
>     self.copy_merra2()
>   File "/gpfsm/dnb44/mathomp4/SystemTests/builds/AGCM/CURRENT/GEOSgcm/install-Re
> lease/bin/remap_upper.py", line 300, in copy_merra2
>     shutil.copy(f, dest)
>   File "/usr/local/other/python/GEOSpyD/4.11.0_py3.9/2022-04-28/lib/python3.9/sh
> util.py", line 427, in copy
>     copyfile(src, dst, follow_symlinks=follow_symlinks)
>   File "/usr/local/other/python/GEOSpyD/4.11.0_py3.9/2022-04-28/lib/python3.9/sh
> util.py", line 264, in copyfile
>     with open(src, 'rb') as fsrc:
> FileNotFoundError: [Errno 2] No such file or directory: '/archive/users/gmao_ops
> /MERRA2/gmao_ops/GEOSadas-5_12_4/d5124_m2_jan10/rs/Y2021/M08/d5124_m2_jan10.fvco
> re_internal_rst.20210809_21z.bin'
> 
>    Per a README by ***@***.*** (or ***@***.***?), the issue is that
>    there was a rewind in MERRA-2 and the new restarts are prefixed by
>    d5124_m2_jun21 in the rewound segments and not d5124_m2_jan10. From
>    what I see the d5124_m2_jun21 restarts are only June to September.
> 
>    —
>    Reply to this email directly, [3]view it on GitHub, or [4]unsubscribe.
>    You are receiving this because you were mentioned. Message ID:
>    ***@***.***>
> 
> References
> 
>    1. https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frlucches&data=05%7C01%7Crobert.a.lucchesi%40nasa.gov%7C09cd153ebbe74802b3d708dacbf5b155%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638046554223051756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=8cWns0MSSJ3ZgCjkZzu2u88E9Dg20SheFVk2odAKkUs%3D&reserved=0
>    2. https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmssolomo&data=05%7C01%7Crobert.a.lucchesi%40nasa.gov%7C09cd153ebbe74802b3d708dacbf5b155%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638046554223051756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=3LqcJAbyjHC%2Fb9Rv0d38lAfRCRZ7xU9ZIe3JBrntXq4%3D&reserved=0
>    3. https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGEOS-ESM%2FGMAO_Shared%2Fissues%2F302&data=05%7C01%7Crobert.a.lucchesi%40nasa.gov%7C09cd153ebbe74802b3d708dacbf5b155%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638046554223051756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=Qv%2FV4Ls8agW3795VajvPLuwuHxoKNmDoeu8EGcjLRYU%3D&reserved=0
>    4. https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAORRJXFM2MUAFLRWMG6L5UDWJPDWFANCNFSM6AAAAAASG7JP7U&data=05%7C01%7Crobert.a.lucchesi%40nasa.gov%7C09cd153ebbe74802b3d708dacbf5b155%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638046554223051756%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C2000%7C%7C%7C&sdata=EUAjruBHSsn22kplhTpXbSKLQdoQNbFafiYQxN0h%2BLY%3D&reserved=0

-- 

-----------------------------------------------------
Rob Lucchesi SSAI         ***@***.***
Global Modeling and Assimilation Office (GMAO)
Operational Software Group            (301) 614-6182
Code 610.1
NASA-Goddard Space Flight Center                           
Greenbelt, MD 20771
-----------------------------------------------------
