### ISSUE TITLE
current tag v.1.10 makes LDAS fail to build

### ISSUE THREAD

**Issue by JustinPerket** [GEOS-ESM/GMAO_Shared#40]
I'm trying to upgrade LDAS's subrepos. Our develop branch is currently on ```v1.0.3```, and something between ```v1.03``` and ```1.0.10``` makes LDAS crash on build. 

**Example of Error:**
```/home/jperket/project/tags/LDASgitTest/parallel_build.o34606053```
 tested with branch of LDAS: ```jperket/PrepForMasterMerge```
most recent commit: ```452838005```

I will update with more info as I understand more. It may be related to our recent switch to use the FVdycoreCubed_GridComp repo.

Content of LDAS's externals:
```
[ESMA_env]
required = True
repo_url = git@github.com:GEOS-ESM/ESMA_env.git
local_path = ./@env
tag = v1.3.2+openmpi
protocol = git

[ESMA_cmake]
required = True
repo_url = git@github.com:GEOS-ESM/ESMA_cmake.git
local_path = ./@cmake
tag = v1.0.9
externals = Externals.cfg
protocol = git

[GMAO_Shared]
required = True
repo_url = git@github.com:GEOS-ESM/GMAO_Shared.git
local_path = ./src/Shared/@GMAO_Shared
tag = v1.0.10
protocol = git
sparse = ../../../config/GMAO_Shared.sparse

[MAPL]
required = True
repo_url = git@github.com:GEOS-ESM/MAPL.git
local_path = ./src/Shared/@MAPL
tag = v1.1.8
protocol = git

[GEOSgcm_GridComp]
required = True
repo_url = git@github.com:GEOS-ESM/GEOSgcm_GridComp.git
local_path = ./src/Components/GEOSldas_GridComp/@GEOSgcm_GridComp
tag = ldas.1
protocol = git
sparse = ../../../../config/GEOSgcm_GridComp_ldas.sparse

[FVdycoreCubed_GridComp]
required = True
repo_url = git@github.com:GEOS-ESM/FVdycoreCubed_GridComp.git
local_path = ./src/Components/GEOSldas_GridComp/@FVdycoreCubed_GridComp
tag = v1.0.6
externals = Externals.cfg
protocol = git

[externals_description]
schema_version = 1.0.0

```

The long term solution is, LDAS's nightly test should point to branches for GMAO_Shared (and MAPL, and now FVdycoreCubed_GridComp.

Right now, figuring this out seems to be a prerequisite for us to use the #39

**Comment by mathomp4** [comment]
I'm fairly certain the answer is you need to add the FMS external to both `Externals.cfg` and `Develop.cfg` as the latest `GMAO_Shared` does not have FMS inside anymore. Let me do a test build or two and find out.

**Comment by mathomp4** [comment]
@JustinPerket I made a PR to `GEOSldas` with the fixes I think work on the branch `bugfix/mathomp4/add-external-fms` to your trial master merge branch.

**Comment by JustinPerket** [comment]
Awesome, thanks @mathomp4 ! I figured it was something FMS related, but would have taken me a while to figure out. Will try https://github.com/GEOS-ESM/GEOSldas/pull/45

**Comment by mathomp4** [comment]
@JustinPerket Let me know if it works. I'm hoping to get in the "move getco2" PRs today so that you can do a final test of your request.
