### ISSUE TITLE
Wrong cice grid files

### ISSUE THREAD

**Issue by yvikhlya** [GEOS-ESM/GMAO_Shared#85]
Currently we write cice grid files in binary format, and default for intel compiler is to write long byte record instead of byte. We write grid_cice.bin and kmt_cice.bin with wrong record size and read with wrong record size, so everything is working with intel compiler, but not with gfortran. And if we correct grid files, all our currently running experiments will crash. How it is better to fix this problem?

**Comment by sanAkel** [comment]
If we do not write binary, but, let's say we write a netCDF, and of course read netCDF, is it fixable? Is that a possible approach to fix?

**Comment by yvikhlya** [comment]
@sanAkel @zhaobin74 I guess cice needs binary. To fix this we need to regenerate every resolution we currently use.

**Comment by sanAkel** [comment]
Since we are counting down the CICE4 days... let's hold on to these thoughts...  and think of alternatives

**Comment by zhaobin74** [comment]
@sdrabenh, I am not sure @mathomp4 's commit is supposed to be fix for this issue. @yvikhlya has got an update from me. He can follow up.

**Comment by sanAkel** [comment]
@sdrabenh why is this "Wrong cice grid files" closed? 

I don't think we incl @yvikhlya ,  @zhaobin74 have a solution for the CICE grids.

Please reopen! Thanks!
